# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=500)),
                ('actionTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('timeInHours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='punished',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_punished', to='public.User'),
        ),
        migrations.AddField(
            model_name='log',
            name='punishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Punishment'),
        ),
        migrations.AddField(
            model_name='log',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_punisher', to='public.User'),
        ),
    ]
