# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('token', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('uses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='Unknown', max_length=500)),
                ('actionTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('timeInHours', models.IntegerField(default=0)),
                ('appealWaitHours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('discord', models.BooleanField(default=False)),
                ('avatar', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log',
            name='punished',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_punished', to='public.Member'),
        ),
        migrations.AddField(
            model_name='log',
            name='punishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Punishment'),
        ),
        migrations.AddField(
            model_name='log',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_punisher', to='public.Member'),
        ),
    ]
