# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='invite',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
