# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('token', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('uses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='key',
            field=models.CharField(default=public.models.get_random_32_string, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='punished',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_punished', to='public.Member'),
        ),
        migrations.AlterField(
            model_name='log',
            name='reason',
            field=models.TextField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='log',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_punisher', to='public.Member'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='member',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
