# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='key',
        ),
        migrations.AlterField(
            model_name='log',
            name='actionTime',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
