# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type_decision',
            field=models.CharField(choices=[('manual', 'manual'), ('progression', 'progression')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='public.Server'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
