# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20171029_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishment',
            name='appealWaitHours',
            field=models.IntegerField(default=0),
        ),
    ]
