# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20171106_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('discord_user', models.BooleanField(default=False)),
            ],
        ),
    ]
