# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
