# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20171106_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='public.Server'),
            preserve_default=False,
        ),
    ]
