# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20171106_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='punishment',
            name='appealWaitHours',
        ),
        migrations.RemoveField(
            model_name='punishment',
            name='timeInHours',
        ),
        migrations.AddField(
            model_name='log',
            name='appealWaitHours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='timeInHours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
