# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20171110_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='staff',
        ),
        migrations.AddField(
            model_name='member',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
