# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
