# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20171110_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
