# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20171113_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='read',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='spam',
        ),
        migrations.AddField(
            model_name='mail',
            name='state',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read'), ('resolved', 'resolved'), ('spam', 'spam')], default='unread', max_length=50),
        ),
    ]
