# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_auto_20171113_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('mail', 'mail'), ('appeal', 'appeal')], default='mail', max_length=50),
        ),
    ]
