# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_mail_appeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='type',
        ),
    ]
